version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  spring:
    container_name: nagne_backend
    image: tlarbals824/nagne_backend
    expose:
      - 8080
    ports:
      - 80:8080