name: cd

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make application-prod.yml
        run: |
          cd ./src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.APPLICATION_PROD }}" > ./application-prod.yml
        shell: bash

      - name: Make application-auth.yml
        run: |
          cd ./src/main/resources
          touch ./application-auth.yml
          echo "${{ secrets.APPLICATION_AUTH }}" > ./application-auth.yml
        shell: bash

      - name: Make application-aws.yml
        run: |
          cd ./src/main/resources
          touch ./application-aws.yml
          echo "${{ secrets.APPLICATION_AWS }}" > ./application-aws.yml
        shell: bash

      - name: Build With Gradle
        run: ./gradlew build
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_ID }}/my_recipe:latest

      - name: Deploy to Prob
        uses: appleboy/ssh-action@master
        id: deploy-prob
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}
            touch ./docker-compose.yml
            echo  "${{ secrets.DOCKER_COMPOSE }}" > ./docker-compose.yml
            docker stop ${{ secrets.DOCKER_REPO }}
            docker rm ${{ secrets.DOCKER_REPO }}  
            docker-compose up -d
